# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title                   : "nibble"
title_separator         : "-"
locale                  : "en-US"
name                    : "Sorakrit Chonwattanagul"
email                   : sorchon@gmail.com
description             : Just a small little blog for the things I find going through topics in the programming world.
baseurl                 : "/" # the subpath of your site, e.g. /blog
url                     : "https://keptsecret.github.io" # the base hostname & protocol for your site, e.g. http://example.com
teaser                  : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                    : "/assets/images/logo.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
minimal_mistakes_skin   : "default" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search                  : true
github_username         : keptsecret
words_per_minute        : 200
repository              : "keptsecret/keptsecret.github.io"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-151010899-1"
    anonymize_ip: false # default
google_site_verification: "hWOTgyuznw9E6GoXXsp-avH_TvqhGyxnz02u3Btr-wc"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# relative_permalinks: false
breadcrumbs: true
include: ["_pages"]
github: [metadata]

author:
  name    : "Sorakrit Chonwattanagul"
  avatar  : "/assets/images/bio-pic.jpg"
  bio     : "Former computer science student with interests in computer vision and graphics; Godot contributor; occasional Blender enthusiast"
  location: "Bangkok, Thailand; Atlanta, GA"
  links:
    - label: "About page"
      icon: "fas fa-fw fa-link"
      url: "/about/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/keptsecret"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sorakrit-chonwattanagul/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/keptsecret"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sorakrit-chonwattanagul/"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
